# Generated by Django 4.0.10 on 2023-06-20 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_event_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='capacity',
            new_name='maximum_capacity',
        ),
        migrations.AddField(
            model_name='event',
            name='mode',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='total_booking',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('event_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
